apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-train-app
  labels:
    app: argocd-train-app
    env: preprod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-train-app
      env: preprod
  template:
    metadata:
      labels:
        app: argocd-train-app
        env: preprod
    spec:
      containers:
      - name: argocd-train-app
        image: ghcr.io/ahmadnurhidayat/argocd-train:v0.9
        imagePullPolicy: IfNotPresent
        workingDir: /app
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: secret
        - name: MYSQL_DB
          value: todos
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-train-app-svc
spec:
  selector:
    app: argocd-train-app
    env: preprod
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP